name: KeepUpThePace
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
#  quiver: "^0.29.0+1"
  args: "^1.0.0"

dev_dependencies:
  test: ^0.12.30
